server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://0822c80a-2aff-407d-a23e-1c517f456bd5.internal.kr1.mariadb.rds.nhncloudservice.com:3306/BoardsService
    username: MSA_User
    password: P@ssw0rd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
